printWidth: 100
semi: false
singleQuote: true
tabWidth: 2
trailingComma: 'none'
"importOrder": ["^@core/(.*)$", "^@server/(.*)$", "^@ui/(.*)$", "^[./]"]
vueIndentScriptAndStyle: false
htmlWhitespaceSensitivity: "ignore"
importOrderSeparation: true
importOrderSortSpecifiers: true
"plugins": ["@trivago/prettier-plugin-sort-imports"]
