"""Add Loan, Client and other improvements

Revision ID: 0498fe435f4a
Revises: 2c68bdc132be
Create Date: 2023-12-10 01:32:59.448643

"""
from typing import Sequence, Union

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision: str = "0498fe435f4a"
down_revision: Union[str, None] = "2c68bdc132be"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "clients",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("name", sa.String(), nullable=False),
        sa.Column("email", sa.String(), nullable=True),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_table(
        "book_copies",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("serial_number", sa.String(), nullable=False),
        sa.Column("book_id", sa.Integer(), nullable=False),
        sa.Column("is_available", sa.Boolean(), nullable=False),
        sa.ForeignKeyConstraint(
            ["book_id"],
            ["books.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        op.f("ix_book_copies_serial_number"), "book_copies", ["serial_number"], unique=True
    )
    op.create_table(
        "loans",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("client_id", sa.Integer(), nullable=False),
        sa.Column("book_copy_id", sa.Integer(), nullable=False),
        sa.Column("loan_date", sa.Date(), nullable=False),
        sa.Column("return_date", sa.Date(), nullable=True),
        sa.Column("penalty_fee", sa.Integer(), nullable=True),
        sa.Column("penalty_fee_paid", sa.Boolean(), nullable=True),
        sa.ForeignKeyConstraint(
            ["book_copy_id"],
            ["book_copies.id"],
        ),
        sa.ForeignKeyConstraint(
            ["client_id"],
            ["clients.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.drop_index("ix_books_isbn", table_name="books")
    op.create_index(op.f("ix_books_isbn"), "books", ["isbn"], unique=True)
    op.create_index(op.f("ix_categories_name"), "categories", ["name"], unique=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f("ix_categories_name"), table_name="categories")
    op.drop_index(op.f("ix_books_isbn"), table_name="books")
    op.create_index("ix_books_isbn", "books", ["isbn"], unique=False)
    op.drop_table("loans")
    op.drop_index(op.f("ix_book_copies_serial_number"), table_name="book_copies")
    op.drop_table("book_copies")
    op.drop_table("clients")
    # ### end Alembic commands ###
